spring:
  application:
    name: remind-pack-scrapper-svc
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  output:
    ansi:
      enabled: always
  cloud:
    refresh:
      enabled: false
    loadbalancer:
      eager-load:
        clients: scraper-puppeteer-svc

log4j2:
  configuration:
    allowed-protocols: "file, https, jar, resource"

